#!/usr/bin/env python
"""
This script is the standalone/script version of dicom2nifti

@author: abrys
"""

import argparse
import os
import dicom2nifti.convert_directory as convert_directory

parser = argparse.ArgumentParser(description='dicom2nifti, convert dicom files into nifti format.')
parser.add_argument('input_directory', type=str,
                    help='directory containing dicom files, can be nested')
parser.add_argument('output_directory', type=str,
                    help='directory to store the nifti files')

parser.add_argument('--no-compression', action='store_true',
                    help='disable gzip compression and write .nii files instead of .nii.gz')

parser.add_argument('--no-reorientation', action='store_true',
                    help='disable image reorientation (default: images are reoriented to LAS orientation)')

args = parser.parse_args()

if not os.path.isdir(args.input_directory):
    print('ERROR: \'input_directory\' should be a valid path')
    print('----------------------------------------------------\n')
    parser.print_help()
elif not os.path.isdir(args.output_directory):
    print('ERROR: \'output_directory\' should be a valid path')
    print('----------------------------------------------------\n')
    parser.print_help()
else:
    convert_directory.convert_directory(args.input_directory,
                                        args.output_directory,
                                        not args.no_compression,
                                        not args.no_reorientation)
